-- AlterTable
ALTER TABLE "Order"
ADD COLUMN IF NOT EXISTS "deliveryCharge" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "deliverySlot" TEXT,
ADD COLUMN IF NOT EXISTS "deliveryDate" TIMESTAMP(3);
