-- AlterTable
ALTER TABLE "BusinessSettings" 
ADD COLUMN IF NOT EXISTS "deliveryRadius" DOUBLE PRECISION DEFAULT 20,
ADD COLUMN IF NOT EXISTS "deliveryRadiusEnforced" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "deliverySlabs" JSONB,
ADD COLUMN IF NOT EXISTS "deliverySlots" JSONB,
ADD COLUMN IF NOT EXISTS "surcharges" JSONB;

-- AlterTable
ALTER TABLE "Order"
ADD COLUMN IF NOT EXISTS "deliveryCharge" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "deliverySlot" TEXT,
ADD COLUMN IF NOT EXISTS "deliveryDate" TIMESTAMP(3);
