-- Enable the pgvector extension to work with embedding vectors (optional, but good for future)
create extension if not exists vector;

-- Sessions Table
create table if not exists sessions (
  session_id uuid primary key default gen_random_uuid(),
  user_id text,
  start_time timestamptz default now(),
  end_time timestamptz,
  summary text,
  duration_seconds integer
);

-- Event Logs Table
create table if not exists event_logs (
  id bigint generated by default as identity primary key,
  session_id uuid references sessions(session_id) on delete cascade,
  timestamp timestamptz default now(),
  event_type text not null check (event_type in ('user', 'ai', 'tool', 'system')),
  content text,
  metadata jsonb
);

-- Enable Row Level Security (RLS) - For now we can leave it open or simple for the backend service role
alter table sessions enable row level security;
alter table event_logs enable row level security;

-- Policy to allow all operations for now (Simplify development)
-- IN PRODUCTION: You would restrict this to only the service role or authenticated users
create policy "Enable all for everyone" on sessions for all using (true);
create policy "Enable all for everyone" on event_logs for all using (true);
