name: Frontend Deploy

on:
  push:
    branches:
      - cicd
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Frontend
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            export PATH=$PATH:/home/ubuntu/n/bin

            cd /opt/apps/villagkart/cicd-test/

            git checkout cicd

            git pull origin cicd

            cd frontend

            npm install

            npm run build

            sudo systemctl reload nginx
